- resources/views/backend/includes/header.blade.php
- resources/views/backend/includes/sidebar.blade.php
Changed the heading and sidebar Names from the king Anthony Rappa to the loged in admin:
access()->user()->name
> Access wrapper

- composer.json
This was missing since last commit where the database/factories/ModelFactory.php was added.
> Added "fzaninotto/faker": "~1.4" to composer.json

- app/Http/Controllers/Backend/Access/PermissionController.php
- app/Http/Controllers/Backend/Access/RoleController.php
- app/Http/Controllers/Backend/Access/UserController.php
- resources/lang/en/alerts.php
- resources/lang/pt-BR/alerts.php
First of all, your project is fantastic !!
I started a study with your project and I'm sending language changes.
Will be my first contributions pull requests on github.
I have reviewed all implementations of the messages before you pull.
Any procedure that I can do better during the pull request, please let me know.
> Translations for alert messages in crud operations. pt-BR and en

- resources/lang/es/alerts.php
- resources/lang/es/auth.php
- resources/lang/es/crud.php
- resources/lang/es/labels.php
- resources/lang/es/menus.php
- resources/lang/es/navs.php
- resources/lang/es/pagination.php
- resources/lang/es/passwords.php
- resources/lang/es/roles.php
- resources/lang/es/strings.php
- resources/lang/es/validation.php
- resources/lang/vendor/log-viewer/es/general.php
- resources/lang/vendor/log-viewer/es/levels.php
- resources/views/backend/includes/header.blade.php
- resources/views/backend/lang/es/welcome.blade.php
- resources/views/frontend/includes/nav.blade.php
> Spanish translation

- resources/lang/fr-FR/alerts.php
- resources/lang/fr-FR/auth.php
- resources/lang/fr-FR/crud.php
- resources/lang/fr-FR/labels.php
- resources/lang/fr-FR/menus.php
- resources/lang/fr-FR/navs.php
- resources/lang/fr-FR/pagination.php
- resources/lang/fr-FR/passwords.php
- resources/lang/fr-FR/roles.php
- resources/lang/fr-FR/strings.php
- resources/lang/fr-FR/validation.php
I translated nearly every strings in french. Some of them are still WIP as I can not yet see clearly the context in which they are used.
> French translations

- app/Http/Controllers/Global/LanguageController.php
- app/Http/Routes/Global/Lang.php
> move lang/ route into a seperate controller, LanguageController

- readme.md
Just a small fix.
I love what you have done with the readme and wiki, great work, this is awesome! :+1:
> Added missing #anchor to features link

- resources/lang/pl/alerts.php
- resources/lang/pl/auth.php
- resources/lang/pl/crud.php
- resources/lang/pl/labels.php
- resources/lang/pl/menus.php
- resources/lang/pl/navs.php
- resources/lang/pl/pagination.php
- resources/lang/pl/passwords.php
- resources/lang/pl/roles.php
- resources/lang/pl/strings.php
- resources/lang/pl/validation.php
Maybe it is not perfect but should work for Poles ;)
> Added Polish translation

- resources/views/backend/access/banned.blade.php
- resources/views/backend/access/deactivated.blade.php
- resources/views/backend/access/deleted.blade.php
- resources/views/backend/access/index.blade.php
- resources/views/backend/access/roles/index.blade.php
- resources/views/backend/access/roles/permissions/index.blade.php
I stumbled  upon this while i wanted to manage my users from my phone. This will make it possible.
> add table-responsive for all tables in "Access Management"

- database/factories/ModelFactory.php
Fixed `User` model namespace for factory use.
> Fix User model namespace

- resources/lang/en/buttons.php
- resources/lang/fr-FR/buttons.php
- resources/views/backend/access/deleted.blade.php
My first though was to have 3 different branches, 3 different PR but I messed up big time and everything was fucked up. Dont wanna touch gulp or git for a couple of days I feel.. Gah.. Gonna get some sleep.
**Sorry for all the messed up PR i made by mistake.. I didn't find a way to remove PR completely..?**
But here it comes. This should fix it all.
> bugfix translation for deleted users action buttons

- app/Http/Middleware/LocaleMiddleware.php
- resources/lang/en/menus.php
- resources/lang/fr-FR/menus.php
- resources/lang/it/menus.php
- resources/lang/sv/menus.php
- resources/views/includes/partials/lang.blade.php
When i was adding my own language. I felt that the process was a bit "scary" or at least I did not feel very comfortable it at first. I was double checking a lot that I was in the right file etc..
These comments are supposed serve as a comforting guide in the process of adding a new language.
> Localisation comment instructions

- resources/lang/pt-BR/menus.php
This PR is a part of #254 :smile:
> improve english translate on menu

- app/Http/Middleware/LocaleMiddleware.php
- resources/lang/de/alerts.php
- resources/lang/de/auth.php
- resources/lang/de/buttons.php
- resources/lang/de/exceptions.php
- resources/lang/de/http.php
- resources/lang/de/labels.php
- resources/lang/de/menus.php
- resources/lang/de/navs.php
- resources/lang/de/pagination.php
- resources/lang/de/passwords.php
- resources/lang/de/roles.php
- resources/lang/de/strings.php
- resources/lang/de/validation.php
- resources/lang/es/menus.php
- resources/lang/fr/menus.php
- resources/lang/it/menus.php
- resources/lang/pt-BR/menus.php
- resources/lang/sv/menus.php
- resources/views/backend/lang/de/access/roles/associated-permissions-explanation.blade.php
- resources/views/backend/lang/de/access/roles/permissions/dependencies-explanation.blade.php
- resources/views/backend/lang/de/welcome.blade.php
- resources/views/includes/partials/lang.blade.php
I've added the german translation and fixed some of the TODOs in other translations
> Add german translation

- resources/lang/de/menus.php
Fixed the issue you mentioned in #260
> Translate menus (german)

- resources/views/backend/access/roles/index.blade.php
Fixing the #269 hardcoded text in `resources/views/backend/access/roles/index.blade.php`
> fix #269 removed hardcoded text in .../roles/index.blade.php

- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2015_12_28_171741_create_social_logins_table.php
- database/migrations/2015_12_29_015055_setup_access_tables.php
The fields created_at and updated_at are setted together to CURRENT_TIMESTAMP wich is mySQL and PostgreSQL valid.
#257
> Set default timestamp for date fileds

- database/seeds/Access/PermissionDependencyTableSeeder.php
There is just 21 permissions at the moment
> Seeder : loop to 21 permissions

- database/seeds/Access/PermissionDependencyTableSeeder.php
Handles future issues related to #276 and #250.
> Remove hardcoded value (21) in PermissionDependencyTableSeeder.php

- app/Models/Access/Permission/Permission.php
- app/Models/Access/Permission/PermissionDependency.php
- app/Models/Access/Permission/PermissionGroup.php
- app/Models/Access/Role/Role.php
Models parent constructor should be called in case child constructor is defined.
> Fixed models __construct method

- resources/lang/da/exceptions.php
- resources/lang/de/exceptions.php
- resources/lang/en/exceptions.php
- resources/lang/es/exceptions.php
- resources/lang/fr/exceptions.php
- resources/lang/it/exceptions.php
- resources/lang/pt-BR/exceptions.php
- resources/lang/sv/exceptions.php
Addresses issue #342 
This PR fixes route for resend key in exceptions tranlation files.
> Fix routes for resend in exceptions translation files

- resources/lang/fr/passwords.php
> Update french translation

- app/Services/Access/Traits/ConfirmUsers.php
- resources/lang/da/exceptions.php
- resources/lang/de/exceptions.php
- resources/lang/en/exceptions.php
- resources/lang/es/exceptions.php
- resources/lang/fr/exceptions.php
- resources/lang/it/exceptions.php
- resources/lang/pt-BR/exceptions.php
- resources/lang/sv/exceptions.php
> Fixed frontend resend confirmation email route.

- config/app.php
> Fix indent for app.name

- resources/lang/de/strings.php
Just noticed it when i looked over the test page, should be no problem to merge :)
> Small fix in German Lanugage strings.php

- resources/views/backend/access/includes/partials/header-buttons.blade.php
The old permission names have been replaced with the new ones.
> Fixed to correct permission name checking.

- app/Repositories/Backend/Access/User/EloquentUserRepository.php
You're able to chain "logging in as" other users, then when you do, when you opt to log back in as the admin user, you're stuck as someone who may potentially not be you.
My solution simply overwrites the temp_user_id in the session and logs in as that user if they are not the same as the currently mocked user, or the admin user.
Edit: My PHP CS Fixer also did some automated code styling.
> Fix being able to chain temp logins.

- resources/lang/fr/buttons.php
- resources/lang/fr/exceptions.php
- resources/lang/fr/history.php
- resources/lang/fr/labels.php
- resources/lang/fr/menus.php
- resources/lang/fr/passwords.php
- resources/lang/fr/strings.php
- resources/lang/fr/validation.php
- resources/views/backend/lang/fr/welcome.blade.php
Typos and untranslated strings
> Updated french translations

- app/Http/Controllers/Backend/Access/User/UserController.php
- app/Http/Routes/Backend/Access.php
- app/Providers/RouteServiceProvider.php
As I've explained in #438
I believe this needs to be removed.
> Remove explicit route binding for User model

- resources/views/backend/includes/sidebar.blade.php
Access module is for managing users, the icon will have the reflection of that :)
> font awesome icon update user -> users

- resources/lang/es/buttons.php
> Update buttons.php third time

- app/Http/Controllers/Backend/Access/User/UserTableController.php
- app/Repositories/Backend/Access/User/UserRepository.php
- resources/views/backend/access/deactivated.blade.php
- resources/views/backend/access/deleted.blade.php
- resources/views/backend/access/index.blade.php
fixes #515
Now the changes don't affect the code style.
> added tweaks to the users datatbles to allow searching

- app/Repositories/Backend/Access/Role/RoleRepository.php
Now when rating a user the roles have dissapeared. This fixes that.
> fix roles fetching

- .gitignore
This is for the Netbeans users
> `/nbproject` added

- resources/views/backend/includes/header.blade.php
Font Awesome Icons has been updated on the sidebar and i think the headed area has been overlooked. I use the header area this was, and am creating this PR so that other can start this way.
> FontAwesome icon added on the header area

- config/mail.php
> Allow self signed SSL certifficates

- config/access.php
- resources/views/frontend/includes/nav.blade.php
- routes/Frontend/Access.php
<<<<<<< HEAD
Allows configuration in .env of whether the site allows user self registrations
=======
We have some sites where the administrator must create accounts.
>>>>>>> release/4.0.0
> Configurable site registration

- config/locale.php
- resources/lang/ar/menus.php
- resources/lang/da/menus.php
- resources/lang/de/menus.php
- resources/lang/el/alerts.php
- resources/lang/el/auth.php
- resources/lang/el/buttons.php
- resources/lang/el/exceptions.php
- resources/lang/el/history.php
- resources/lang/el/http.php
- resources/lang/el/labels.php
- resources/lang/el/menus.php
- resources/lang/el/navs.php
- resources/lang/el/pagination.php
- resources/lang/el/passwords.php
- resources/lang/el/roles.php
- resources/lang/el/strings.php
- resources/lang/el/validation.php
- resources/lang/es/menus.php
- resources/lang/fr/menus.php
- resources/lang/it/menus.php
- resources/lang/nl/menus.php
- resources/lang/pt_BR/menus.php
- resources/lang/sv/menus.php
- resources/lang/th/menus.php
This is Greek localization pack, not complete.
> Greek translation

- config/locale.php
- resources/lang/ar/menus.php
- resources/lang/da/menus.php
- resources/lang/de/menus.php
- resources/lang/el/menus.php
- resources/lang/en/menus.php
- resources/lang/es/menus.php
- resources/lang/fr/menus.php
- resources/lang/id/alerts.php
- resources/lang/id/auth.php
- resources/lang/id/buttons.php
- resources/lang/id/exceptions.php
- resources/lang/id/history.php
- resources/lang/id/http.php
- resources/lang/id/labels.php
- resources/lang/id/menus.php
- resources/lang/id/navs.php
- resources/lang/id/pagination.php
- resources/lang/id/passwords.php
- resources/lang/id/roles.php
- resources/lang/id/strings.php
- resources/lang/id/validation.php
- resources/lang/it/menus.php
- resources/lang/nl/menus.php
- resources/lang/pt_BR/menus.php
- resources/lang/sv/menus.php
- resources/lang/th/menus.php
- resources/lang/vendor/log-viewer/id/general.php
- resources/lang/vendor/log-viewer/id/levels.php
Hi, This is a Language Pack. Indonesian.
> Indonesia Language Pack

- resources/views/vendor/log-viewer/_template/master.blade.php
Fix RTL View for log-viewer when switching to RTL language.
> Fix RTL language for log-viewer

- resources/lang/fr/navs.php
In French profile is spelled "profil", without the E at the end
> Updating french translation

- tests/Backend/Forms/Access/RoleFormTest.php
- tests/Frontend/Routes/LoggedOutRouteTest.php
when role_must_contain_permission and locale.status are false, don't run some tests
> skip some tests when config options are false

- resources/views/backend/access/deactivated.blade.php
- resources/views/backend/access/deleted.blade.php
- resources/views/backend/access/index.blade.php
- resources/views/backend/access/roles/index.blade.php
This will update to the latest version of Datatables, 1.10.15, plus it shows an example of how to add an Export to Excel button.
> use Datatables cdn

- resources/assets/sass/frontend/pages/_dashboard.scss
- resources/views/frontend/includes/nav.blade.php
I think users would appreciate a visual indication of where they are, just as is done for the backend.
> Enhancement: add active class to frontend navbar items

- resources/assets/sass/frontend/_global.scss
- resources/views/backend/access/create.blade.php
- resources/views/backend/access/deactivated.blade.php
- resources/views/backend/access/deleted.blade.php
- resources/views/backend/access/edit.blade.php
- resources/views/backend/access/index.blade.php
- resources/views/frontend/auth/register.blade.php
- resources/views/frontend/user/account/tabs/edit.blade.php
A few things needed adjustments.
> Updates for new last_name field

- .travis.yml
This pull request fix travis.yml step error like this ↓
https://travis-ci.org/rappasoft/laravel-5-boilerplate/jobs/230342027
https://github.com/rappasoft/laravel-5-boilerplate/pull/719#issuecomment-300174159
> Fix travis.yml step error

- resources/lang/fr/validation.php
Missing French translation for first_name and last_name frontend attributes.
> Missing French translation

- app/Http/Controllers/Frontend/ContactController.php
- app/Mail/Frontend/Contact/SendContact.php
- resources/views/frontend/contact.blade.php
- resources/views/frontend/mail/contact_text.blade.php
These changes fill in more fields for the contact email (like Reply To and a text version of the message) that make dealing with the message in the recipient's email program a little easier.
> contact form updates

- composer.lock
- resources/views/frontend/auth/login.blade.php
- resources/views/frontend/auth/passwords/email.blade.php
- resources/views/frontend/auth/passwords/reset.blade.php
- resources/views/frontend/auth/register.blade.php
- resources/views/frontend/contact.blade.php
- resources/views/frontend/index.blade.php
- resources/views/frontend/layouts/app.blade.php
- resources/views/frontend/user/account.blade.php
- resources/views/frontend/user/account/tabs/change-password.blade.php
- resources/views/frontend/user/account/tabs/edit.blade.php
- resources/views/frontend/user/dashboard.blade.php
Frontend views updated and and made responsive. 
Related with: https://github.com/rappasoft/laravel-5-boilerplate/issues/788
> Responsive Frontend

- app/Http/Controllers/LanguageController.php
- resources/views/frontend/includes/nav.blade.php
Changing the locale of the application issue has been resolved.
> Fix locale change

- resources/views/backend/auth/user/index.blade.php
This looks to be working fine.
I haven't noticed it breaking or anything. Simple HTML edit.
> Added dropdowns to the breadcrumb links

- app/Repositories/Backend/Auth/RoleRepository.php
- app/Repositories/Backend/Auth/UserRepository.php
- resources/views/backend/auth/role/create.blade.php
- resources/views/backend/auth/role/edit.blade.php
- resources/views/backend/auth/user/create.blade.php
- resources/views/backend/auth/user/edit.blade.php
- Fixed a bug where all permissions could not be removed from a User or Role (even not required in the app config option). 
- Fixed label for attr for email confirmation on User creation
- Added CoreUI switch styling to checkboxes on backend Users and Roles.
> Fix removing all permissions and add CoreUI Switches

- database/migrations/2017_09_03_144628_create_permission_tables.php
Already Removed this in https://github.com/spatie/laravel-permission/pull/490
> Already removed

- routes/backend/admin.php
Additional route for admin index,
> Admin index. (redirect)

- resources/views/vendor/log-viewer/logs.blade.php
- resources/views/vendor/log-viewer/show.blade.php
Fixes table responsiveness on large screens
> Fixed table-responsive on large screens

- app/Repositories/BaseRepository.php
Error on login with socialite (eg: facebook).
> Fix bug can not get item by column on BaseRepository

- resources/views/backend/auth/role/index.blade.php
- resources/views/backend/auth/user/create.blade.php
- resources/views/backend/auth/user/deactivated.blade.php
- resources/views/backend/auth/user/deleted.blade.php
- resources/views/backend/auth/user/index.blade.php
- resources/views/backend/auth/user/show/tabs/overview.blade.php
- resources/views/frontend/user/account/tabs/profile.blade.php
- resources/views/vendor/log-viewer/logs.blade.php
- resources/views/vendor/log-viewer/show.blade.php
> Fix table responsive

- resources/views/backend/auth/role/index.blade.php
- resources/views/backend/auth/user/create.blade.php
- resources/views/backend/auth/user/deactivated.blade.php
- resources/views/backend/auth/user/deleted.blade.php
- resources/views/backend/auth/user/edit.blade.php
- resources/views/backend/auth/user/index.blade.php
- resources/views/backend/auth/user/show/tabs/overview.blade.php
- resources/views/frontend/user/account/tabs/profile.blade.php
- resources/views/vendor/log-viewer/logs.blade.php
- resources/views/vendor/log-viewer/show.blade.php
Went back to the old wrapping method till there is an official fix
> Fix table-responsive with wrap method

- composer.lock
- tests/Backend/Routes/Auth/UserRouteTest.php
- tests/Frontend/Routes/LoggedOutRouteTest.php
I fixed a few of the tests and did a composer dupate, please have a look and merge if everything is ok. Thank you :)
> fix some tests + composer update

- composer.lock
- resources/views/frontend/contact.blade.php
- tests/Backend/Forms/Auth/UserFormTest.php
- tests/Frontend/Forms/LoggedOutFormTest.php
fix some tests, fix contact form, composer update
> fix some tests, fix contact form, composer update

- webpack.mix.js
> Fix npm run hot issue with mix versioning

- resources/views/backend/auth/role/index.blade.php
- resources/views/backend/auth/user/index.blade.php
- resources/views/backend/dashboard.blade.php
- resources/views/frontend/auth/login.blade.php
- resources/views/frontend/auth/passwords/email.blade.php
- resources/views/frontend/auth/passwords/expired.blade.php
- resources/views/frontend/auth/passwords/reset.blade.php
- resources/views/frontend/auth/register.blade.php
- resources/views/frontend/index.blade.php
Add title to home page style: "Laravel 5.5 Boilerplate | Home" style used in backend
> Fix some title to some pages and corrected titles not translated

- composer.json
- composer.lock
- phpunit.xml
Added [PHPUnit Pretty Result Printer](https://packagist.org/packages/codedungeon/phpunit-result-printer).
With this package, we can see Prettier test cases results. Please find an attached
screenshot.
> Add phpunit-result-printer for Pretty Tests Result Printer

- app/Helpers/Frontend/Auth/Socialite.php
This Pull Request has only a small change in the Socialite Helper Class but the solution is so simple. Just write the count($socialite_enable) output to a variable and use this.
> Small Performance Improvement in Socialite Helper Class

- .circleci/config.yml
We should leverage continuous integration in this project.
A big Pro of this is that we could see in Pull Requests if anything is breaking.
As an open source project it's also good to signalize any visitor that this project is backed by ci with a badge.
> Enhancement: add circle ci config

- .babelrc
- .circleci/config.yml
- package.json
- readme.md
- tests/Javascript/Example.spec.js
- yarn.lock
This PR adds a frontend test suite based on facebook/jest with a first test for the ExampleComponent.
It also triggers test runs in circle ci.
> Enhancement: Add Frontend test suite

- composer.json
> Routes on formatter

- tests/Feature/Backend/User/ChangeUserPasswordTest.php
- tests/Feature/Backend/User/CreateUserTest.php
- tests/Feature/Backend/User/DeleteUserTest.php
fix phpunit issue when i changed default language
> fix phpunit issue when i changed default language

- app/Models/Auth/Traits/Attribute/UserAttribute.php
fix tooltips on UserAttribute and btn-group in action buttons
> fix show/edit buttons and tooltips

- resources/views/frontend/user/dashboard.blade.php
Add missing title in frontend dashboard
> Add missing title in frontend dashboard

- resources/lang/es/menus.php
Add history translation and correction in some transalations
> Add history translation and correction

- resources/sass/frontend/app.scss
- webpack.mix.js
see https://laravel-news.com/laravel-5-7-resources-directory-changes
and https://github.com/rappasoft/laravel-5-boilerplate/issues/1138
> Make assets compatible with Laravel 5.7 npm run

- tests/Javascript/Example.spec.js
> Changed example file location

- app/Http/Controllers/Frontend/Auth/PasswordExpiredController.php
- app/Http/Controllers/Frontend/Auth/RegisterController.php
- routes/frontend/auth.php
Removed config() helper from route.
Laravel runs it's routes before the tests. 
The config helper placed in the routes were being parsed before the override in the unit tests.
> Fixed issue #1157

- resources/views/frontend/user/account/tabs/edit.blade.php
- Added laravel @method() function to fix it
Fixed issues :  #1183 #1178
> Fixed Duplicate Element Issue in Browser Console

- package.json
- resources/js/bootstrap.js
- resources/js/plugins.js
Updates the Sweetalert2 JS library to the latest version
> Sweetalert2 JS version 8.x library update code changes

- resources/views/includes/partials/messages.blade.php
Re issue #1195
HTML not being rendered in flash messages, eg on the login page when user is not verified, which means the link is not rendered:
> Fix issue with HTML not being rendered in message

- tests/Feature/Backend/User/ReadUsersTest.php
#enhancement
assert that not only is the response successful, but that the user is on the correct view.
> add assertions to ReadUsersTest

- resources/sass/backend/app.scss
- resources/views/backend/auth/user/index.blade.php
> Fixed inaccessible dropdown on user management page

- app/Http/Requests/Frontend/Auth/RegisterRequest.php
- app/Repositories/Backend/Auth/SocialRepository.php
- tests/Feature/Backend/User/ClearSessionTest.php
- tests/Feature/Backend/User/ConfirmUserTest.php
- tests/Feature/Backend/User/DeactivateUserTest.php
- tests/Feature/Backend/User/ManageUserSocialTest.php
Update namespace to comply with psr-4 autoloading standard
> Namespace fix

- tests/Feature/Frontend/PasswordExpirationTest.php
- tests/Feature/Frontend/ResetPasswordTest.php
Signed-off-by: Hariadi Hinta <diperakui@yahoo.com>
> Make test compatible with any locale

- resources/views/backend/includes/sidebar.blade.php
- resources/views/vendor/log-viewer/bootstrap-4/_master.blade.php
Mostly ported from v6 forward.   Missing Breadcrumbs and side menu highlighting.
> Backend : Improve log page integration

- database/migrations/2019_08_19_000000_create_failed_jobs_table.php
Fixes https://github.com/rappasoft/laravel-boilerplate/issues/1501
See https://github.com/laravel/laravel/commit/d6eda444a7daf19a0e27861d5e06cb43e71da497
> Add UUID column to failed_jobs table
