- composer.json
- composer.lock
- config/app.php
- resources/views/backend/includes/sidebar.blade.php
Hi!
I don't know if this is the direction that you want to go. But i find it nice to have this [active menu plugin letrunghieu/active](https://github.com/letrunghieu/active).
This can be used on nav li items to set an class of active.
```<li class="{{ Active::pattern('admin/access/*') }}"><a href="{!!url('admin/access/users')!!}"><span>User      Management</span></a></li>```
In this case, the nav link to "User Management" stays active while you browse through roles and permission.
When i ran my composer update after my installation of letrunghieu/active my composer.lock file found some updates, dont know if you want to merge those in to so I made it in a separate commit in that case.
This is just a suggestion, I will keep on adding this myself every time i clone your repo so i figured …
> Active menu state in admin-panel

- gulpfile.js
Fixes bugg with **Gulp** less compilation where the output file name was `main.less` instead of `main.css` in **gulpfile.js**
I am a less lover and for that I am proud, @rappasoft 
:wink:
> fix for issue #53 gulp less to css output filename

- resources/views/backend/lang/sv/welcome.blade.php
I actually had this one sitting in my other project but forgot to include it. I only thought of `resources/lang` how come that it is in `backend/lang`?
Would be nice to add it into  `resources/lang`  instead? Make it an `welcome.php` language file instead of blade as of now? It would still be possible to insert the links to your site and the github repo. 
````
//welcome.php
Blah bla bla :link-to-rappa-website bla ...... bla :link-to-github bla bla
````
That way keep it all in one place?
> Added sv translation to backend/welcome.blade.php

- resources/views/backend/includes/sidebar.blade.php
- resources/views/backend/lang/sv/welcome.blade.php
So now if you click *Log Viewer -> Dashboard* the dropdown will stay open and *Dashboard* get an `active` state.
Ofc also works for `/admin/log-viewer/logs`
> Active state log viewer dropdown sidebar

- config/app.php
> Typo that causes composer to crash on Linux systems

- app/Http/Controllers/Frontend/Auth/PasswordController.php
- app/Models/Access/User/User.php
- app/Repositories/Frontend/Auth/EloquentAuthenticationRepository.php
If user has been banned or deactivated by an Admin he can't log in with the social account.
This should fix: https://github.com/rappasoft/laravel-5-boilerplate/issues/141
I have also added a small fix in  postEmail method.  
In this way we can check if the email input is filled and the value is a valid email, everything before execute any query.
> Prevent user login with social account if banned or deactivate

- app/Http/Requests/Frontend/Access/ChangePasswordRequest.php
When you register, it doesn't check for "alpha_num" but when you change the password, it checks for it. I suggest to take it out.
> alpha_num unnecessary

- resources/lang/fr-FR/validation.php
Just a translation error.
Before : means the field already exists
After : means th e field doesn't exists
> validation exists fr-FR message changed

- config/compile.php
This PR solves the issue #193 
The `BusServiceProvider.php` was removed on 5.2 version.
Thanks
> removed the BusServiceProvider.php include on config/compile.php

- app/Models/Access/Permission/Traits/Relationship/PermissionRelationship.php
- app/Models/Access/Role/Traits/Relationship/RoleRelationship.php
use to show below error:
---
FatalErrorException in Model.php line 1011:
Class name must be a valid object or a string
---
on 
admin/access/roles and admin/access/roles/permissions
> Rectified belongsToMany() in users function in RoleRelationship & PermissionRelationship

- resources/lang/en/labels.php
Since it says *All Groups/Permissions* in the dropdown I would like to add it to the tab description as well.
> locale - add "All *" for the permission/group tabs

- resources/lang/en/labels.php
- resources/lang/fr-FR/labels.php
- resources/lang/sv/labels.php
- resources/views/backend/access/deactivated.blade.php
- resources/views/backend/access/deleted.blade.php
- resources/views/backend/access/index.blade.php
- resources/views/backend/access/roles/index.blade.php
- resources/views/backend/access/roles/permissions/index.blade.php
Pluralizations for the access tables. 
**Note** 2 of the Swedish translations have the same word independent of singular or plural. Just wanna inform that it is not a duplication.
This PR will not break anything. But, one possibly major thing is that the pluralization trans_choice() does not seem to work at all for the fr-FR version. Soo strange! So as of now, the singular sting is shown all the time for French and only French. I checked the Swedish words that doesn't change normally and that worked. And the English version works just as expected. So its something really fishy about the fr-FR translation here.. I dont understand!
> locale pluralization for number of rows in access tables

- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2015_12_28_171741_create_social_logins_table.php
- database/migrations/2015_12_29_015055_setup_access_tables.php
With MySQL 5.5, you should not have a default value of `CURRENT_TIMESTAMP` on more then one column at the same time. Also, a column added with no default
>  it is the same as specifying both `DEFAULT CURRENT_TIMESTAMP` and `ON UPDATE CURRENT_TIMESTAMP`.
>              (https://dev.mysql.com/doc/refman/5.5/en/timestamp-initialization.html)
This PR will remove the default current timestamps, and ensure that no default value is set on them.
> Remove the default value on updated_at columns

- config/laravel-backup.php
Excluded the `node_modules` folder from the backup.
Not in this PR, but I'd also opt to not exclude `storage_path()`, since user uploads tend to be stored there sometimes.
> Exclude node_modules from backup

- resources/views/vendor/log-viewer/show.blade.php
Allow to show log stack. Ex: Email log has a confirmation link, but cannot see, need to enable stack viewer to see the link.
> Enable log stack viewer

- .env.example
This made me waste a few minutes as I didn't notice it.
MAIL_* env should be next to each other, after all.
> Remove duplicate MAIL_DRIVER from .env

- config/backend.php
- resources/views/backend/layouts/master.blade.php
I had to change it on my own. Probably useful if it is in config.
I copied the layout first line descriptions from the main Admin LTE theme documentation, then added my interpretation of it on the second line.
Sidebar mini was not in the documentation but it I do use it and i think it is missing from their docs.
> Configure adminlte layout via config file

- resources/views/backend/access/create.blade.php
Incredibly minor fix. The placeholder is set to the label instead of the input on the creation form in the admin backend
> Fix placeholder on user creation

- database/DisableForeignKeys.php
The key for db should be 'pgsql' instead of 'postgres' to avoid the "unknown index: pgsql" Error when using Postgres as your database and execute seed command.
> Rename driver name to 'pgsql' for Postgres

- package.json
- tests/BrowserKitTestCase.php
- tests/TestCase.php
Enhancement for running tests on Gitlab CI.
When running these the tests on Gitlab CI, I experienced the error "Mysql: Too many connection". This was due to the fact that per test, another connection was used. This is now fixed by adding a teardown function to disconnect from the database after the tests.
> Add teardown function to test cases

- database/TruncateTable.php
Solve the truncate problem with Postgres and restarting the primary key Identity.
> Fix Truncate table command for Postgres DB

- resources/views/frontend/user/dashboard.blade.php
Make sure larger profile images do not break the layout of page
Constrains the user profile image size on the dashboard page so that it does not break the page layout if the user loads a larger profile image
> Add size for profile image on Dashboard page

- app/Listeners/Backend/Access/User/UserEventListener.php
- app/Repositories/Backend/History/EloquentHistoryRepository.php
To reproduce: Create a new user, delete, then delete permanently. In the Dashboard Recent History it will say "Admin Istrator permanently deleted user {user}" (instead of the actual user name).
This patch will show the correct user name (as plain text, not a link) for all history occurrences.
> Permanently deleting user needs updates to history log

- app/Http/Requests/Backend/Access/Role/StoreRoleRequest.php
- app/Http/Requests/Backend/Access/Role/UpdateRoleRequest.php
- app/Http/Requests/Backend/Access/User/StoreUserRequest.php
- app/Http/Requests/Backend/Access/User/UpdateUserRequest.php
- app/Http/Requests/Frontend/Auth/RegisterRequest.php
- app/Http/Requests/Frontend/User/UpdateProfileRequest.php
- resources/views/backend/access/change-password.blade.php
- resources/views/backend/access/create.blade.php
- resources/views/backend/access/edit.blade.php
- resources/views/backend/access/roles/create.blade.php
- resources/views/backend/access/roles/edit.blade.php
- resources/views/frontend/auth/login.blade.php
- resources/views/frontend/auth/passwords/email.blade.php
- resources/views/frontend/auth/passwords/reset.blade.php
- resources/views/frontend/auth/register.blade.php
- resources/views/frontend/user/account/tabs/change-password.blade.php
- resources/views/frontend/user/account/tabs/edit.blade.php
On the front end this PR changes all Form::input() calls to the more specific Form:name(), Form::email() and Form::password(). In addition it makes required fields actually be required, sets autofocus to the first field on a form, and sets maxlength for name and email fields.
On the backend name and email fields are limited to a max length of 191 characters.
The maxlength is due to a change in Laravel 5.4, as described here:
https://laravel-news.com/laravel-5-4-key-too-long-error
string fields like name and email are now defined in MySQL as varchar(191) utf8mb4_unicode_ci.
Passing more than 191 characters to the db for fields defined this way throws a "String data, right truncated: 1406 Data too long for column" error.
Although in practice it may be unlikely to see this error as most …
> Standardize use of LaravelCollective formbuilder functions

- app/helpers.php
Since glob() function have unexpected output in some systems it is probably a good idea to replace it with more consistent one (recursiveDirectoryIterator & recursiveIteratorIterator).
This is a fix. Form the official php glob() description it is known that the function have unexpected behaviors like :  
> On some systems it is impossible to distinguish between empty match and an error.
> This function isn't available on some systems (e.g. old Sun OS).
>  The GLOB_BRACE flag is not available on some non GNU systems, like Solaris.
So i have created this function with the more appropriate method to avoid this and other similar issues.
[PHP glob() doc](http://php.net/manual/en/function.glob.php)
> Replace glob() function usage

- resources/assets/sass/backend/app.scss
The Source Sans Pro font is referenced in several places in the backend.
> Fix: Add Source Sans Pro font import

- app/Http/Controllers/Frontend/Auth/ResetPasswordController.php
The sendResetResponse() method needs to be overridden to show the success message, which makes the redirectPath() method unnecessary.
> Password reset not showing success message

- webpack.mix.js
This pull request prevents excess generated JS and CSS while in development mode.
In the code currently, `npm run dev` will generate .js and .css files with a version appended to the end of the filename. Since each new compile is versioned, new files created and the public/css & public/js are filled with unnecessary files. This pull request implements what's suggested in the Laravel Docs [https://laravel.com/docs/5.4/mix#versioning-and-cache-busting](https://laravel.com/docs/5.4/mix#versioning-and-cache-busting) and only utilizes versioning when compiling for production. Dev compiles will reuse the same files each compile.
> Only version the js and css when compiling for production

- app/Repositories/Frontend/Access/User/UserRepository.php
Separate First name and Last name when using Social Login and user does not exist.
Works and Tested with BitBucket, Facebook, Google, GitHub, LinkedIn and Twitter. Atleast with my name it works. I don't know how it feels when people have more than two first names or last names.
Credit to christostsang - http://stackoverflow.com/questions/32407604/laravel-socialite-first-and-last-name
> Separate First name and Last name when using Social Login

- app/Http/Requests/Request.php
The old method `forbiddenResponse` was replaced with `failedAuthorization` as per [commit](https://github.com/laravel/framework/commit/1a7540967ca36f875a262a22b76c2a094b9ba3b4).
> Changed default permission in Request, override failedAuthorization

- app/Helpers/Frontend/Auth/Socialite.php
- config/no-captcha.php
From https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0:
"If you are using the config:cache command during deployment, you must make sure that you are only calling the env function from within your configuration files, and not from anywhere else in your application."
> use env() and config() instead of getenv()

- app/Providers/AppServiceProvider.php
Issue: Laravel generates a RuntimeException in the CLI with encrypted sessions when running `php artisan`. 
[RuntimeException]                                 
No application encryption key has been specified.
The fix allows a new key to be generated with 'php artisan key:generate' with no current APP_KEY specified in a new .env file.
> Added fix when running php artisan in CLI with no APP_KEY.

- app/Providers/AppServiceProvider.php
- resources/views/backend/auth/role/index.blade.php
- resources/views/backend/auth/user/deactivated.blade.php
- resources/views/backend/auth/user/deleted.blade.php
- resources/views/backend/auth/user/index.blade.php
Changed the default Laravel AbstractPaginator class to use the built in Bootstrap 4 blade templates.
Moved pagination out of the Bootstrap 'card-footer' as it was causing the pagination to display as table.
> Added Boostrap 4 templates as default pagination view

- app/Repositories/Backend/Auth/UserRepository.php
On the Backend UserRepository, a user's roles and permissions are queried individually when viewing the Role Management page. This fix eager loads the roles and permissions, reducing number of queries from 57 to 9 on a page with the default 25 paginated users.
> Fix for n+1 issue on Backend/Auth/UserRepository.php

- composer.json
- composer.lock
Right now you're not able to perform "schema" updates because you get an exception:
```
[RuntimeException]                                                                   
Changing columns for table "users" requires Doctrine DBAL; install "doctrine/dbal".
```
According to laravels documentation ([migrations#modifying-columns](https://laravel.com/docs/5.5/migrations#modifying-columns)) it's required to have `doctrine/dbal` installed.
> Added doctrine/dbal ^2.6 to allow schema updates

- app/Http/Requests/Frontend/Auth/RegisterRequest.php
- config/app.php
As soon as you try to submit the registration form with activated NoCaptcha then you'll get an missing member-Exception because NoCaptcha's validation-rule usage for Laravel 5.5 got changed.  Additionally it's not required to register the alias anymore.
> Fixes google's no captcha validation

- app/Repositories/Frontend/Auth/UserRepository.php
I was quite irritated why I didn't saw the my providers image. This PR will set the correct avatar_type when a user registers or when he reauthenticates with the provider.
> Set default avatar_type when registered/logged in via socialite 

- .gitignore
- composer.json
- composer.lock
The[ laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) is a very useful package. 
with the commands `php artisan ide-helper:generate` and `php artisan ide-helper:meta` you can create files that you IDE gets auto completion on Laravel Facades etc.
Especially for contributors of this project it's nice to have the helper.
> Enhancement: add barryvdh/laravel-ide-helper as dependency

- app/Http/Controllers/Frontend/Auth/SocialLoginController.php
When using laravel-5-boilerplate 5.6 on a default homestead using google social login will fail with the error :: 
count(): Parameter must be an array or an object that implements Countable
Hopefully this fixes and is backwards compatible.
> php 7.2 compatibility in social auth

- resources/assets/sass/frontend/app.scss
This is fix of the position for importing custom.scss to allow override bootstrap more easily. Before this fix, if you want to override some style of bootstrap, you have to use `!important`, which is not desirable.
> move import custom.scss position to allow overide bootstrap more easily

- resources/views/backend/includes/sidebar.blade.php
Describe what the PR does, try to first give a brief explanation and then a more in depth explanation if you think that is necessary.
on the sidebar, when we click on user and log-viewer menu, I added active classes
> active link in backend for user and log viewer links

- resources/views/frontend/contact.blade.php
Fix not translated "Contact us" in title page
> Fix not translated "Contact us"

- app/Models/Auth/Traits/Attribute/UserAttribute.php
added "btn-group-sm" also to the dropdown on the UserManagment page.
So the icons get vertically-centered.
> Fixes Button Missallignment in BE/UserManagment

- app/Repositories/BaseRepository.php
This PR adds the magic method __call to the BaseRepository to add query scopes easily to repository queries on the fly. It also replaces implode with the spread operator when setting the scopes because implode was causing all parameters to be sent as one parameter, just comma deliminated. 
Adding the scopes through magic methods makes sense to me since it is more like Eloquent this way, which makes it more intuitive to use.
> Update repository scopes

- resources/js/frontend/app.js
Instances of `[Vue warn]: Failed to mount component: template or render function not defined.` on default clone of repo. Sorta makes it more consistent with Laravel/Laravel.
This will give support for JeffreyWay/laravel-mix v4.0.0 and up which needs CommonJS syntax for EcmaScript modules.
JeffreyWay mentioned this in the "Breaking" section here: https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0
with a matching commit here: https://github.com/laravel/laravel/commit/dc58f95ebbf15b8902ccaef4e2aaa6b0ecbb0e96
to finally a PR here: https://github.com/laravel/laravel/pull/4882
Note that this has not been persisted to the compiled assets in this PR as it is producing the error fixed in https://github.com/rappasoft/laravel-5-boilerplate/pull/1182.
> Added `.default` to Vue component requires

- webpack.mix.js
Currently resources in CSS get loaded only if you host your site on "domain.xy". This will work even if you have your Laravel on "domain.xy/app/public".
Fix found on: https://www.samundra.com.np/integrating-font-awesome-with-laravel-5.x-using-webpack/1574
> setting resource root

- .php_cs.dist
- composer.json
This is a enhancement
The past configuration of [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) didn't do much and [StyleCI](https://styleci.readme.io/) haved always to do the work.
Now I've looked on StyleCI  [Laravel presets](https://styleci.readme.io/docs/presets#section-laravel) (outdated by the way) and configurate PHP-CS-Fixer by myself.
I must warn you that some configurations are a little opinionated, so I decided to leave the first use of the fixer for you @rappasoft, because a lot of files will be changed and you will be able to decide which configuration to keep.
PS: You can check some examples on [php-cs-fixer-configurator](https://mlocati.github.io/php-cs-fixer-configurator/#)
> Using PHP-CS-Fixer the right way

- package-lock.json
- package.json
A prototype pollution vulnerability exists in jQuery versions < 3.4.0 that allows an attacker to inject properties on Object.prototype.
> - Security fix, upgrade jQuery.

- config/services.php
Google plus API seems to be gone, default Socialite values seem to work without causing warnings.
> Use default Socialite Google scopes

- database/migrations/2017_09_11_174816_create_social_accounts_table.php
Change from string to text because Google avatar addresses can be greater than 255 characters.
> Modify avatar field type on app.social_accounts table

- app/Helpers/Global/SystemHelper.php
Rename the global function so it is more descriptive to use in other places
e.g. in side-bar blade to auto include 'modules'
Made the original function call the renamed version to be backwards compatible
> Rename include_route_files to include_files_in_folder

- readme.md
Update the link of the StyleCI badge to point to the StyleCI dashboard for this repository instead of the badge image.
> [Enhancement][Docs] Readme.md: Update link on StyleCI badge

- resources/views/frontend/user/account/tabs/edit.blade.php
The class "form-control" adds a gray border around the form input, "form-control-file" is the class used for bootstrap file inputs: https://getbootstrap.com/docs/4.0/components/forms/#form-controls.
Describe what the PR does, try to first give a brief explanation and then a more in depth explanation if you think that is necessary.
> Update form-control-file class

- resources/lang/de/labels.php
'greate_new' should be 'create_new'
This is a **fix** of the typo that came with [this commit](https://github.com/rappasoft/laravel-boilerplate/commit/88ac38ea8c05398b8b8971b4eacf85f44087d293).
> [Translations] Fix typo in de/labels.php

- app/Models/Traits/Uuid.php
**Booting and Initializing**
The difference between both is very simple: the boot{Trait} works statically, while the initialize{Trait} works dynamically. The boot will affect all instances of the Model, while the initializing will work only for its instance.
https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Eloquent/Model.php#L222
Fyi, CreateUserTest fail when setup Uuid trait with migration (uuid not null)
> Follow the pattern boot{Trait} on Model

- resources/views/vendor/log-viewer/bootstrap-4/_master.blade.php
When viewing the log dashboard and log viewer, bootstrap files were being loaded from maxpath.bootstrapcdn.com. The correct url for those is stackpath.bootstrapcdn.com as seen here, [https://www.bootstrapcdn.com/legacy/bootstrap/](https://www.bootstrapcdn.com/legacy/bootstrap/)
> Direct links for bootstap files to correct cdn

- .github/workflows/main.yml
Hi! I noticed that on new repos the Github workflow is not running, since the new repos use "main" instead of the "master" branch. I believe adding the "main" branch might be useful :D
> Add main as a branch to run the workflow on

- app/Domains/Auth/Http/Middleware/TwoFactorAuthenticationStatus.php
When logging in when ADMIN_REQUIRES_2FA=false in .env, the successful admin redirect could point to "/admin", but the TwoFactorAuthenticationStatus middleware checks for 
`$request->is('admin/*')`
which fails the test and shows the 2fa requirement page. Going to any other admin page does not show the 2fa requirement page. This small change catches the 'admin' url by changing 
`$request->is('admin/*')`
to 
`$request->is('admin*')`
> Fixes 2fa disabled, but still shows when route is '/admin'
